### ISSUE TITLE
Request for color preview in Shader Editor

### ISSUE THREAD

**Issue by erlingpaulsen** [Qubus0/GodotColorPreview#4]
Hi,

First of all, this looks like a great and simple plugin, thank you!

I'm currently using Godot v4.0-alpha11 and the plugin is working as expected in the Script Editor. However, it does not seem to work in the Shader Editor, which I guess is expected. Do you have any plans to make it work for the Shader Editor as well? It would be really useful.

**Comment by Qubus0** [comment]
hey there. good idea. I didn't really think about the shader editor at all so far.
In general: it should be possible. The shader editor is also a TextEdit/CodeEdit. It's not as easy to find in the Editor Scene tree though (at least I didn't find a method to get the bottom tool dockers)

The other question for me - since i don't have a clue about shaders: how do you distinguish a color? isn't it just a vec4 like any other vec4? theoretically you could take any line which has the comment // color in it. that would be pretty manual though.

**Comment by erlingpaulsen** [comment]
Yes, any `vec4` could in theory be used as encoding a color, so I think the main use case would be for shader uniforms, which is the same as an export variables in GDScript. Shader uniforms can be declared with type hints, to add the proper UI to edit the shader parameters in the Godot editor. In Godot 4, the type hint for color is `source_color`, for example:

`uniform vec4 input_color : source_color = vec4(0.5, 0.46, 0.33, 1.0);`

I think this is the only way to reliably distinguish color variables without any manual hacks. It would be a very nice feature at least!

**Comment by Qubus0** [comment]
That is good to know, thank you. I will look into it :)
