### ISSUE TITLE
broken in shader editor (Godot 4.1.1)

### ISSUE THREAD

**Issue by TheLegoSensei** [Qubus0/GodotColorPreview#9]
it doesn't seem to do anything in the shader editor for me, but it does in GDscript just fine. this tool would be great and help my project immensely (doing a ton of palette swapping) so I hope there's an easy fix. also, does it work on vec3 colors? my code is using vec3s and I tried swapping them into vec4 but that didn't work either.

**Comment by Qubus0** [comment]
sadly i'm not very familiar with shaders, so I wasn't able to cover it all.

this code here ([ColorPreview.gd L336-L352](https://github.com/Qubus0/GodotColorPreview/blob/main/addons/ColorPreview/ColorPreview.gd#L336-L352)) covers "detecting" a color in a line of code - the last one covers the shaders - you might be able to adjust it for your use case. 


```gdscript
func match_color_in_string(string: String) -> RegExMatch:
	var re = RegEx.new()
	var color

	re.compile("Color\\((?<params>(?R)*.*?)\\)")
	color = re.search(string)
	if color != null:
		return color

	re.compile("Color\\.(?<const>[A-Z_]+)\\b")
	color = re.search(string)
	if color != null:
		return color

	re.compile("source_color.*?vec4\\((?<params>(?R)*.*?)\\)")
	color = re.search(string)
	return color
```

It uses regex to find a color and also put it into one of two named groups (`params` for rgb type colors and `const` for color names). right now shader colors are only found if they start with `source_color` and are a vec4, that's why your vec3s aren't caught. And, as far as I know, there is no other "guaranteed" way to figure out if something is a color or just some other vector (that was discussed in #4). If you know anything else about this, please let me know. 

Maybe a regex like this https://regex101.com/r/ij2HDu/1 would work for you? it just replaces vec4 with vec3 (note that the regex in code all use double \\\\ instead of single \\, since the backslashes need to be escaped for gdscript).

**Comment by TheLegoSensei** [comment]
oh I see... yes it is responding in the top when I declare the uniforms with vec4, which is apparently not something I tried.

I changed the block of code you sent to the following:
	re.compile("vec3\\((?<params>(?R)*.*?)\\)")
	color = re.search(string)
	if color != null:
		return color
		
	re.compile("vec4\\((?<params>(?R)*.*?)\\)")
	color = re.search(string)
	return color
and in my use case this is nice, although this does assume the vec3's and vec4's are colors, which I can do with my shaders as they're 2D pixel shaders, but many people wouldn't want this behavior for 3D shaders, although vec4's are nearly always colors, and the color display on the side doesn't really get in the way if you're using the vector as coordinates, it just might be a bit distracting to some... idk. now I wonder if there's a way to have settings so the user could tell it what they consider a color... anyway thanks for your help and now this works great for me!
